### ISSUE TITLE
Prevent Via, Via 3 and Via HTML from proxying themselves or each other

### ISSUE THREAD

**Issue by seanh** [hypothesis/checkmate#33]
See also:

* [Incident report: Via DOS’d by trying to proxy itself recursively](https://docs.google.com/document/d/1A5cZEXjetC_QpQma72ddRTN3_PPIfgwCzgRApHRtIoc/)
* [Block invalid URLs with `200` instead of responding with `400`](https://github.com/hypothesis/checkmate/issues/34)

## Problem

You can ask Via to recursively proxy itself (`https://via.hypothes.is/https://via.hypothes.is/https://via.hypothes.is/…`) and this will cause it to use up all its CPU and memory and take the service down.

## Solution

Prevent Via, Via 3, and Via HTML, QA and prod, from proxying themselves or each other. Any URL beginning with any of `https://via.hypothes.is`, `https://qa-via.hypothes.is`, `https://via3.hypothes.is`, etc should be blocked for all Via's.

Checkmate or checkmatelib might be the best place to implement this so that it doesn't need to be implemented separately for each Via.

This [quick hack](https://github.com/hypothesis/via/pull/269) can be removed from Via once this is done.

**Comment by jon-betts** [comment]
The following items have been added to the blocklist and should prevent this from happening:

```
## Via, don't proxy yourself.
via.hypothes.is via-loop
via3.hypothes.is via-loop
viahtml3.hypothes.is via-loop
qa-via.hypothes.is via-loop
qa-via3.hypothes.is via-loop
qa-viahtml3.hypothes.is via-loop
```
