### ISSUE TITLE
Block invalid URLs with 200 instead of responding with 400

### ISSUE THREAD

**Issue by seanh** [hypothesis/checkmate#34]
See also:

* [Prevent Via, Via 3 and Via HTML from proxying themselves or each other](https://github.com/hypothesis/checkmate/issues/33)

During a [recent incident](https://docs.google.com/document/d/1A5cZEXjetC_QpQma72ddRTN3_PPIfgwCzgRApHRtIoc/) we observed that Via was attempting to proxy really, really long URLs (`https://via.hypothes.is/https://via.hypothes.is/https://via.hypothes.is/…`). In Checkmate's Papertrail logs we could see that Checkmate was responding with 400 Bad Request to Via's queries about these URLs, and I believe this was causing Via to "fail open" and proxy the URLs.

If the URL is invalid or too long Checkmate should respond with 200 and a JSON body explaining that the URL is blocked, so that services don't attempt to proxy these URLs. The `"reason"` in the JSON body can be used to indicate that the URL is blocked because it's seen as invalid, so the client can treat these specially if it wants to. But a better default behaviour, for all Via's, is to fail closed for these URLs rather than fail open, so Checkmate should indicate that they're blocked.

**Comment by jon-betts** [comment]
We can tackle this another way as well, which is to truncate them in `checkmatelib` before they are sent. Our current matching only cares about the domain, so unless the domain is 10000 chars long it doesn't matter.

**Comment by jon-betts** [comment]
I don't think there's much we can do about this on the checkmate side. The get request is already too long to process, so we can only 400. We've already merged a "fix" to prevent calls from checkmatelib from getting that long. Hopefully that's enough
