### ISSUE TITLE
Pick and register with an external threat detection system

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#4]
If we choose to use [Google Web Risk](https://cloud.google.com/web-risk), then we will need to contact them before we can do anything. This might take some time, so we should probably get ahead with this work.

The sign up for the API (to contact sales) is: https://go.chronicle.security/webriskapi

We have to be whitelisted to use it, so I guess they may want to check we aren't pedalling malware or something.

**Comment by ajpeddakotla** [comment]
Contacted Google to get a quote and sign up for the service. Will update when I hear back.

**Comment by ajpeddakotla** [comment]
Working on this issue has officially solidified my disdain for Google's Admin platform. Nothing is straightforward on Google's platform. I've spent hours trying to figure out how to set this up and I'm still not sure if things are squared away. 

Here's the steps I took: 
1. Gave @jon-betts access to the Google Cloud Platform as part of the H org
2. Set up account info for Web Risk/Google Cloud Platform - forwarded the email I received to Jon
3. After the account setup, I was taken to [this page](https://console.cloud.google.com/getting-started/enterprise?organizationId=466088845067), which I just cannot figure out. So maybe @jon-betts, we can sync up on this tomorrow when we're both online?

**Comment by jon-betts** [comment]
Yeah not sure about that. We can try and work through it together if you like

**Comment by jon-betts** [comment]
Seeing as this isn't going very well. We're starting a parallel track to use https://urlhaus.abuse.ch/

This would have protected us from at least some of the threats and should be easier to integrate

**Comment by jon-betts** [comment]
I'm fairly sure this is done now, but we're going to do the URLHaus stuff as a stepping stone first.
